const actions = {
    ADD_TODO:  'ADD_TODO',
    SET_TODO_COMPLETED: 'SET_TODO_COMPLETED',
    SET_VISIBILITY: 'SET_VISIBILITY',
    UI_FREEZE: 'UI_FREEZE',
    UI_UNFREEZE: 'UI_UNFREEZE',
    SHOW_ERROR: 'SHOW_ERROR',
    HIDE_ERROR: 'HIDE_ERROR'
};

export default actions;
